-- FarmSim EDU Phase 5: crops v2 (global catalog + region rates)
-- Generated by scripts/generate-crops-migration.js
SET NAMES utf8mb4;
USE cp393722_farmsim;

-- New tables
CREATE TABLE IF NOT EXISTS crops (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  country_id INT UNSIGNED NOT NULL,
  code VARCHAR(50) NOT NULL,
  name_th VARCHAR(100) NOT NULL,
  name_en VARCHAR(100) NOT NULL,
  category ENUM('field_crop','vegetable','fruit','herb','economic') NOT NULL,
  growth_months TINYINT UNSIGNED NOT NULL DEFAULT 4,
  crop_category ENUM('short','medium','long') NOT NULL DEFAULT 'medium',
  base_coin INT UNSIGNED NOT NULL DEFAULT 100,
  base_buy_price INT NOT NULL DEFAULT 15,
  base_sell_price INT NOT NULL DEFAULT 30,
  capability_bonus TINYINT UNSIGNED NOT NULL DEFAULT 2,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (country_id) REFERENCES countries(id),
  UNIQUE KEY uk_crop_country_code (country_id, code),
  CONSTRAINT chk_crops_growth CHECK (growth_months BETWEEN 1 AND 12)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crop_region_rates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  crop_id INT UNSIGNED NOT NULL,
  region_id INT UNSIGNED NOT NULL,
  suitability_level ENUM('excellent','good','moderate','poor','unsuitable') NOT NULL,
  coin_multiplier DECIMAL(4,2) NOT NULL DEFAULT 1.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_crop_region (crop_id, region_id),
  FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
  FOREIGN KEY (region_id) REFERENCES country_regions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crop_seasons (
  crop_id INT UNSIGNED NOT NULL,
  season_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (crop_id, season_id),
  FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
  FOREIGN KEY (season_id) REFERENCES agricultural_seasons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Drop legacy FKs to region_crops if upgrading
DROP PROCEDURE IF EXISTS farmsim_drop_crop_fks;
DELIMITER //
CREATE PROCEDURE farmsim_drop_crop_fks()
BEGIN
  DECLARE done INT DEFAULT 0;
  DECLARE fk_name VARCHAR(255);
  DECLARE tbl VARCHAR(255);
  DECLARE cur CURSOR FOR
    SELECT TABLE_NAME, CONSTRAINT_NAME
    FROM information_schema.KEY_COLUMN_USAGE
    WHERE TABLE_SCHEMA = DATABASE()
      AND REFERENCED_TABLE_NAME = 'region_crops';
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
  OPEN cur;
  read_loop: LOOP
    FETCH cur INTO tbl, fk_name;
    IF done THEN LEAVE read_loop; END IF;
    SET @s = CONCAT('ALTER TABLE ', tbl, ' DROP FOREIGN KEY ', fk_name);
    PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
  END LOOP;
  CLOSE cur;
END//
DELIMITER ;
CALL farmsim_drop_crop_fks();
DROP PROCEDURE farmsim_drop_crop_fks;

-- Clear dependent data that references old crop IDs
DELETE FROM market_transactions;
DELETE FROM market_prices;
UPDATE player_crop_plans SET crop_id = NULL;

DROP TABLE IF EXISTS region_crop_seasons;
DROP TABLE IF EXISTS region_crops;

DELETE FROM crop_seasons;
DELETE FROM crop_region_rates;
DELETE FROM crops;

-- Thailand crops
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'rice', 'ข้าว', 'Rice', 'field_crop', 4, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'jasmine_rice', 'ข้าวหอมมะลิ', 'Jasmine Rice', 'field_crop', 4, 'medium', 120, 18, 36, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'feed_corn', 'ข้าวโพดเลี้ยงสัตว์', 'Feed Corn', 'field_crop', 4, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'sweet_corn', 'ข้าวโพดหวาน', 'Sweet Corn', 'field_crop', 3, 'short', 100, 15, 30, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'corn', 'ข้าวโพด', 'Corn', 'field_crop', 4, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'sugarcane', 'อ้อย', 'Sugarcane', 'field_crop', 5, 'medium', 110, 17, 33, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'cassava', 'มันสำปะหลัง', 'Cassava', 'field_crop', 5, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'sweet_potato', 'มันเทศ', 'Sweet Potato', 'field_crop', 4, 'medium', 85, 13, 26, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'potato', 'มันฝรั่ง', 'Potato', 'field_crop', 4, 'medium', 95, 14, 29, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'soybean', 'ถั่วเหลือง', 'Soybean', 'field_crop', 4, 'medium', 95, 14, 29, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'mung_bean', 'ถั่วเขียว', 'Mung Bean', 'field_crop', 3, 'short', 80, 12, 24, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'peanut', 'ถั่วลิสง', 'Peanut', 'field_crop', 3, 'short', 90, 14, 27, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'sesame', 'งา', 'Sesame', 'field_crop', 3, 'short', 85, 13, 26, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'sunflower', 'ทานตะวัน', 'Sunflower', 'field_crop', 4, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'cotton', 'ฝ้าย', 'Cotton', 'field_crop', 5, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'cabbage', 'กะหล่ำปลี', 'Cabbage', 'vegetable', 3, 'short', 70, 11, 21, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'chinese_cabbage', 'ผักกาด', 'Chinese Cabbage', 'vegetable', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'napa_cabbage', 'ผักกาดขาว', 'Napa Cabbage', 'vegetable', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'lettuce', 'ผักสลัด', 'Lettuce', 'vegetable', 2, 'short', 70, 11, 21, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'kale', 'คะน้า', 'Kale', 'vegetable', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'bok_choy', 'กวางตุ้ง', 'Bok Choy', 'vegetable', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'morning_glory', 'ผักบุ้ง', 'Morning Glory', 'vegetable', 2, 'short', 60, 9, 18, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'celery', 'ผักกาดหอม', 'Celery', 'vegetable', 3, 'short', 70, 11, 21, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'tomato', 'มะเขือเทศ', 'Tomato', 'vegetable', 3, 'short', 80, 12, 24, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'eggplant', 'มะเขือ', 'Eggplant', 'vegetable', 3, 'short', 75, 11, 23, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'chili', 'พริก', 'Chili', 'vegetable', 3, 'short', 85, 13, 26, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'pumpkin', 'ฟักทอง', 'Pumpkin', 'vegetable', 3, 'short', 75, 11, 23, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'cucumber', 'แตงกวา', 'Cucumber', 'vegetable', 2, 'short', 70, 11, 21, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'watermelon', 'แตงโม', 'Watermelon', 'vegetable', 3, 'short', 90, 14, 27, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'long_bean', 'ถั่วฝักยาว', 'Long Bean', 'vegetable', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'longan', 'ลำไย', 'Longan', 'fruit', 6, 'long', 150, 23, 45, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'lychee', 'ลิ้นจี่', 'Lychee', 'fruit', 6, 'long', 140, 21, 42, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'strawberry', 'สตรอว์เบอร์รี', 'Strawberry', 'fruit', 4, 'medium', 160, 24, 48, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'mandarin', 'ส้มเขียวหวาน', 'Mandarin', 'fruit', 5, 'medium', 130, 20, 39, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'avocado', 'อะโวคาโด', 'Avocado', 'fruit', 6, 'long', 180, 27, 54, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'mango', 'มะม่วง', 'Mango', 'fruit', 5, 'medium', 140, 21, 42, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'banana', 'กล้วย', 'Banana', 'fruit', 4, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'coconut', 'มะพร้าว', 'Coconut', 'fruit', 6, 'long', 120, 18, 36, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'papaya', 'มะละกอ', 'Papaya', 'fruit', 4, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'guava', 'ฝรั่ง', 'Guava', 'fruit', 4, 'medium', 95, 14, 29, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'rose_apple', 'ชมพู่', 'Rose Apple', 'fruit', 4, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'durian', 'ทุเรียน', 'Durian', 'fruit', 6, 'long', 300, 45, 90, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'jackfruit', 'ขนุน', 'Jackfruit', 'fruit', 6, 'long', 150, 23, 45, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'marian_plum', 'มะเฟือง', 'Marian Plum', 'fruit', 5, 'medium', 120, 18, 36, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'sweet_tamarind', 'มะขามหวาน', 'Sweet Tamarind', 'fruit', 5, 'medium', 130, 20, 39, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'pineapple', 'สับปะรด', 'Pineapple', 'fruit', 3, 'short', 110, 17, 33, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'mangosteen', 'มังคุด', 'Mangosteen', 'fruit', 6, 'long', 200, 30, 60, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'rambutan', 'เงาะ', 'Rambutan', 'fruit', 5, 'medium', 140, 21, 42, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'longkong', 'ลองกอง', 'Longkong', 'fruit', 5, 'medium', 130, 20, 39, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'salak', 'สละ', 'Salak', 'fruit', 5, 'medium', 125, 19, 38, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'cempedak', 'จำปาดะ', 'Cempedak', 'fruit', 5, 'medium', 140, 21, 42, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'lime', 'มะนาว', 'Lime', 'fruit', 4, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'rubber', 'ยางพารา', 'Rubber', 'economic', 8, 'long', 150, 23, 45, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'palm_oil', 'ปาล์มน้ำมัน', 'Palm Oil', 'economic', 8, 'long', 160, 24, 48, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'tea', 'ชา', 'Tea', 'economic', 6, 'long', 140, 21, 42, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'arabica_coffee', 'กาแฟอาราบิก้า', 'Arabica Coffee', 'economic', 6, 'long', 180, 27, 54, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'robusta_coffee', 'กาแฟโรบัสตา', 'Robusta Coffee', 'economic', 6, 'long', 160, 24, 48, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'cocoa', 'โกโก้', 'Cocoa', 'economic', 6, 'long', 170, 26, 51, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'macadamia', 'แมคคาเดเมีย', 'Macadamia', 'economic', 8, 'long', 220, 33, 66, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'black_pepper', 'พริกไทย', 'Black Pepper', 'economic', 5, 'medium', 130, 20, 39, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'mulberry', 'หม่อน', 'Mulberry', 'economic', 4, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'bamboo', 'ไผ่', 'Bamboo', 'economic', 5, 'medium', 110, 17, 33, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'eucalyptus', 'ยูคาลิปตัส', 'Eucalyptus', 'economic', 6, 'long', 120, 18, 36, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'garlic', 'กระเทียม', 'Garlic', 'herb', 4, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'shallot', 'หอมแดง', 'Shallot', 'herb', 3, 'short', 80, 12, 24, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'onion', 'หอมหัวใหญ่', 'Onion', 'herb', 4, 'medium', 85, 13, 26, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'ginger', 'ขิง', 'Ginger', 'herb', 4, 'medium', 95, 14, 29, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'turmeric', 'ขมิ้น', 'Turmeric', 'herb', 4, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'galangal', 'กระชาย', 'Galangal', 'herb', 4, 'medium', 95, 14, 29, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'lemongrass', 'ตะไคร้', 'Lemongrass', 'herb', 3, 'short', 75, 11, 23, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'coriander', 'ผักชี', 'Coriander', 'herb', 2, 'short', 60, 9, 18, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'spring_onion', 'ต้นหอม', 'Spring Onion', 'herb', 2, 'short', 60, 9, 18, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'sweet_basil', 'โหระพา', 'Sweet Basil', 'herb', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'holy_basil', 'กะเพรา', 'Holy Basil', 'herb', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'lemon_basil', 'แมงลัก', 'Lemon Basil', 'herb', 2, 'short', 65, 10, 20, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'roselle', 'กระเจี๊ยบแดง', 'Roselle', 'herb', 3, 'short', 80, 12, 24, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'stink_bean', 'สะตอ', 'Stink Bean', 'herb', 5, 'medium', 120, 18, 36, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (1, 'parkia', 'ลูกเนียง', 'Parkia', 'herb', 5, 'medium', 115, 17, 35, 2);

-- USA crops
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_corn', 'Corn', 'Corn', 'field_crop', 4, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_soybean', 'Soybean', 'Soybean', 'field_crop', 4, 'medium', 95, 14, 29, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_wheat', 'Wheat', 'Wheat', 'field_crop', 5, 'medium', 90, 14, 27, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_cotton', 'Cotton', 'Cotton', 'field_crop', 5, 'medium', 110, 17, 33, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_rice', 'Rice', 'Rice', 'field_crop', 4, 'medium', 100, 15, 30, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_peanuts', 'Peanuts', 'Peanuts', 'field_crop', 3, 'short', 85, 13, 26, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_almonds', 'Almonds', 'Almonds', 'economic', 8, 'long', 200, 30, 60, 3);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_grapes', 'Grapes', 'Grapes', 'fruit', 5, 'medium', 150, 23, 45, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_lettuce', 'Lettuce', 'Lettuce', 'vegetable', 2, 'short', 70, 11, 21, 1);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_sorghum', 'Sorghum', 'Sorghum', 'field_crop', 4, 'medium', 85, 13, 26, 2);
INSERT INTO crops (country_id, code, name_th, name_en, category, growth_months, crop_category, base_coin, base_buy_price, base_sell_price, capability_bonus) VALUES (2, 'us_sunflower', 'Sunflower', 'Sunflower', 'field_crop', 3, 'short', 90, 14, 27, 1);

-- Thailand region rates
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'jasmine_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'jasmine_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'jasmine_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'jasmine_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'feed_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'feed_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'feed_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'feed_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'sugarcane';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sugarcane';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'sugarcane';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sugarcane';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'cassava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'cassava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'cassava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'cassava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'potato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'mung_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'mung_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'mung_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'mung_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'peanut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'peanut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'peanut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'peanut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sesame';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sesame';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sesame';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sesame';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sunflower';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sunflower';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'sunflower';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'sunflower';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'chinese_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'chinese_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'chinese_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'chinese_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'napa_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'napa_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'napa_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'napa_cabbage';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'kale';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'kale';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'kale';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'kale';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'bok_choy';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'bok_choy';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'bok_choy';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'bok_choy';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'morning_glory';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'morning_glory';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'morning_glory';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'morning_glory';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'celery';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'celery';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'celery';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'celery';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'tomato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'tomato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'tomato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'tomato';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'eggplant';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'eggplant';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'eggplant';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'eggplant';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'chili';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'chili';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'chili';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'chili';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'pumpkin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'pumpkin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'pumpkin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'pumpkin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'cucumber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'cucumber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'cucumber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'cucumber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'watermelon';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'watermelon';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'watermelon';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'watermelon';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'long_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'long_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'long_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'long_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'longan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'longan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'longan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'longan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'lychee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'lychee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'lychee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'lychee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'strawberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'strawberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'strawberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'strawberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'mandarin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'mandarin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'mandarin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'mandarin';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'avocado';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'avocado';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'avocado';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'avocado';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'mango';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'mango';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'mango';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'mango';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'banana';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'banana';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'banana';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'banana';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'coconut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'coconut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'coconut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'coconut';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'papaya';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'papaya';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'papaya';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'papaya';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'guava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'guava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'guava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'guava';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'rose_apple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'rose_apple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'rose_apple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'rose_apple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'durian';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'durian';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'durian';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'durian';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'jackfruit';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'jackfruit';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'jackfruit';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'jackfruit';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'marian_plum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'marian_plum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'marian_plum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'marian_plum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_tamarind';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_tamarind';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_tamarind';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_tamarind';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'pineapple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'pineapple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'pineapple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'pineapple';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'mangosteen';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'mangosteen';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'mangosteen';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'mangosteen';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'rambutan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'rambutan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'rambutan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'rambutan';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'longkong';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'longkong';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'longkong';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'longkong';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'salak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'salak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'salak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'salak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'cempedak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'cempedak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'cempedak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'cempedak';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'lime';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'lime';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'lime';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'lime';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'rubber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'rubber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'rubber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'rubber';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'palm_oil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'palm_oil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'palm_oil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'palm_oil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'tea';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'tea';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'tea';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'tea';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'arabica_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'arabica_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'arabica_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'arabica_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'robusta_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'robusta_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'robusta_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'robusta_coffee';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'cocoa';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'cocoa';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'cocoa';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'cocoa';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'macadamia';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'macadamia';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'macadamia';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'macadamia';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'black_pepper';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'black_pepper';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'black_pepper';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'black_pepper';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'mulberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'mulberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'mulberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'mulberry';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'bamboo';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'bamboo';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'bamboo';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'bamboo';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'eucalyptus';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'eucalyptus';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'eucalyptus';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'eucalyptus';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'garlic';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'garlic';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'garlic';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'garlic';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'shallot';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'shallot';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'shallot';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'shallot';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'ginger';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'ginger';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'ginger';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'ginger';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'turmeric';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'turmeric';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'turmeric';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'turmeric';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'galangal';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'galangal';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'galangal';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'galangal';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemongrass';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemongrass';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemongrass';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemongrass';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'coriander';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'coriander';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'coriander';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'coriander';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'spring_onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'spring_onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'spring_onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'spring_onion';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'sweet_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'holy_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'holy_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'holy_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'holy_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemon_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemon_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemon_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'lemon_basil';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'roselle';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'good', 0.85 FROM crops c WHERE c.country_id = 1 AND c.code = 'roselle';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'moderate', 0.65 FROM crops c WHERE c.country_id = 1 AND c.code = 'roselle';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'roselle';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'stink_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'stink_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'stink_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'stink_bean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 1, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'parkia';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 2, 'poor', 0.45 FROM crops c WHERE c.country_id = 1 AND c.code = 'parkia';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 3, 'excellent', 1.00 FROM crops c WHERE c.country_id = 1 AND c.code = 'parkia';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 4, 'unsuitable', 0.25 FROM crops c WHERE c.country_id = 1 AND c.code = 'parkia';

-- USA region rates (1.0 native, 0.45 elsewhere)
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_corn';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_soybean';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_wheat';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_wheat';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_wheat';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_wheat';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_cotton';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_rice';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_peanuts';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_peanuts';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_peanuts';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_peanuts';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_almonds';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_almonds';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_almonds';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_almonds';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_grapes';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_grapes';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_grapes';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_grapes';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_lettuce';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sorghum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sorghum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sorghum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sorghum';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 5, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sunflower';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 6, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sunflower';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 7, 'poor', 0.45 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sunflower';
INSERT INTO crop_region_rates (crop_id, region_id, suitability_level, coin_multiplier)
         SELECT c.id, 8, 'excellent', 1.00 FROM crops c WHERE c.country_id = 2 AND c.code = 'us_sunflower';

-- Basic season mapping for Thailand (rainy=1, winter=2, summer=3)
-- Field crops: rainy+summer; vegetables: winter; fruits: varied; economic: long-term
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 1 FROM crops c WHERE c.country_id = 1 AND c.category = 'field_crop';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 3 FROM crops c WHERE c.country_id = 1 AND c.category = 'field_crop';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 2 FROM crops c WHERE c.country_id = 1 AND c.category = 'vegetable';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 3 FROM crops c WHERE c.country_id = 1 AND c.category = 'vegetable';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 1 FROM crops c WHERE c.country_id = 1 AND c.category = 'fruit';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 2 FROM crops c WHERE c.country_id = 1 AND c.category = 'fruit';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 2 FROM crops c WHERE c.country_id = 1 AND c.category = 'herb';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 3 FROM crops c WHERE c.country_id = 1 AND c.category = 'herb';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
         SELECT c.id, 1 FROM crops c WHERE c.country_id = 1 AND c.category = 'economic';
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
     SELECT c.id, 1 FROM crops c WHERE c.country_id = 2;
INSERT IGNORE INTO crop_seasons (crop_id, season_id)
     SELECT c.id, 4 FROM crops c WHERE c.country_id = 2;

-- Re-add FKs to crops table
SET @has_mp_fk = (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE
 WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'market_prices' AND REFERENCED_TABLE_NAME = 'crops');
SET @sql = IF(@has_mp_fk = 0,
 'ALTER TABLE market_prices ADD CONSTRAINT market_prices_crop_fk FOREIGN KEY (crop_id) REFERENCES crops(id)',
 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has_pcp_fk = (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE
 WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'player_crop_plans' AND REFERENCED_TABLE_NAME = 'crops');
SET @sql = IF(@has_pcp_fk = 0,
 'ALTER TABLE player_crop_plans ADD CONSTRAINT player_crop_plans_crop_fk FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE SET NULL',
 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has_mt_fk = (SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE
 WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'market_transactions' AND REFERENCED_TABLE_NAME = 'crops');
SET @sql = IF(@has_mt_fk = 0,
 'ALTER TABLE market_transactions ADD CONSTRAINT market_transactions_crop_fk FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE SET NULL',
 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;